#! /usr/bin/env node

// command-line cluster administration tool

_u = require('underscore');         // REPL Global
_s = require('underscore.string');  // REPL Global

var _ = require('underscore');
var usage = require('./usage');
var h = require('./h');
var repl = require('./repl');

function main() {
    var cmods = replcx['cmods'] = h.load_commands();
    var cmdnames = _.pluck(cmods, 'command');

    // parse command-line into script-args, command-name and
    // command-arguments.
    var scriptargs = [];
    var command = undefined;
    var cmdargs = [];
    for( var i=2; i< process.argv.length; i++ ) {
        var arg = process.argv[i];
        if( command != undefined ) {
            cmdargs = cmdargs.concat( [arg] );
        } else if ( _.contains(cmdnames, arg) ) {
            command = arg;
        } else {
            scriptargs = scriptargs.concat( [arg] );
        }
    }

    var sopts = usage.script( scriptargs );
    var cmod  = cmods[command];
    var conn = h.connection(sopts.argv.c, sopts.argv.u, sopts.argv.p);

    if( cmod != undefined ) {
        copts = cmod.usage( cmdargs );
        copts.argv
        if( copts.argv.h ) {
            console.log( copts.help() );
            process.exit(0);
        } else {
            var options = h.newOptions( conn, copts.argv ); 
            cmod.run( options );
        }
    } else if ( command != undefined ) {
        console.log("Invalid command !");
        console.log( sopts.help() );
        process.exit(2);
    } else if ( sopts.argv.h ) {
        console.log( sopts.help() );
        process.exit(0);
    } else {
        repl.loop( sopts );
    }
}

if( require.main === module ) main();

// vim: filetype=javascript :
